# This is a basic workflow to help you get started with Actions

name: CI-Windows

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          submodules: recursive
          
      # Setup msbuild
      - name: setup-msbuild
        uses: microsoft/setup-msbuild@v1
        
      # Generate sln
      - name: generate-sln
        shell: cmd
        run: |
          @echo | call GenerateProjectFiles.sh
   
      # Build sln
      - name: build-sln
        shell: cmd
        run: |
          @echo | msbuild -m Engine.sln /t:build /p:Configuration="Debug" /p:Platform="x64" /p:BuildInParallel=true
                # Generate and build sln
